# NLP(Natural language processing ) analysis of RESTAURANT  REVIEW dataset:
 * NLP is an area of computer science and artificial intelligence concerned with the interactions between computers and human (natural) languages. 
 * NLP is a part of AI which overlaps with ML & DL to perform tasks. 
## step 1: 
* Importing libraries

In [3]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
ps = PorterStemmer()


C:\ProgramData\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
C:\ProgramData\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


<h1> step 2:</h1><p1>Import dataset with setting sep as '\t' as columns are separated as tab space.</p1>

In [4]:
dataset = pd.read_csv(r"C:\Users\Ankita\Desktop\review.tsv" , sep = "\t")
dataset


Review  Liked
0                             Wow... Loved this place.      1
1                                   Crust is not good.      0
2            Not tasty and the texture was just nasty.      0
3    Stopped by during the late May bank holiday of...      1
4    The selection on the menu was great and so wer...      1
..                                                 ...    ...
995  I think food should have flavor and texture an...      0
996                           Appetite instantly gone.      0
997  Overall I was not impressed and would not go b...      0
998  The whole experience was underwhelming, and I ...      0
999  Then, as if I hadn't wasted enough of my life ...      0

[1000 rows x 2 columns]

## Step 3 : 
<h2> Text Cleaning or Preprocessing :</h2>
<h3>Remove Punctuations, Numbers :</h3> Punctuations, Numbers doesn’t help much in processong the given text, if included, they will just increase the size of bag of words that we will create as last step and decrase the efficency of algorithm.
<h3>Stemming:</h3> Take roots of the word .for example:loved ----> lov,stopped ---->stop...etc.

<h3>Convert each word into its lower case / upper case:</h3> it useless to have same words in different cases (eg: ‘good’ and ‘GOOD’ ).

<h3>Tokenization: </h3> involves splitting sentences and words from the body of the text.



In [5]:
clean_review = []
text = dataset['Review'][0]
for i in range(1000):
    text = re.sub('[^a-zA-Z]',' ',dataset['Review'][i])
    text = text.lower()
    text = text.split()#tokenization
    
    #t1 = [word for word in text if not word in set(stopwords.words('english'))]
    
    text = [ps.stem(word) for word in text if not word in set(stopwords.words('english'))]
    text = ' '.join(text)
    clean_review.append(text)

## Step 4:
<h2>Making the bag of words via sparse matrix</h2>

* Take all the different words of reviews in the dataset without repeating of words.
* One column for each word, therefore there are going to be many columns.
* rows are reviews
* If word is there in row of dataset of reviews, then the count of word will be there in row of bag of words under the column of the word.

For this purpose we need CountVectorizer class from sklearn.feature_extraction.text.
We can also set a max number of features as “max_features”. Do the training on the clean_review and then apply the same transformation to the clean_review “.fit_transform(clean_review)” and then convert it into an array.



In [6]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer( max_features = 900)
X = cv.fit_transform(clean_review)
X = X.toarray()

#x has 1000 rows representing 1000 reviews . But the col are limited 
#to 500 set by max_feature parameter. whlile processing textual data we can 
#get large amount of col. we sort these col by frequency and then keep only
#frequent col representing few frequent words.

y = dataset['Liked'].values
print(X, y)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]] [1 0 0 1 1 0 0 0 1 1 1 0 0 1 0 0 1 0 0 0 0 1 1 1 1 1 0 1 0 0 1 0 1 0 1 1 1
 0 1 0 1 0 0 1 0 1 0 1 1 1 1 1 1 0 1 1 0 0 1 0 0 1 1 1 1 1 1 1 0 1 1 1 0 0
 0 0 0 1 1 0 0 0 0 1 0 1 0 1 1 1 0 1 0 1 0 0 1 1 0 1 1 1 1 1 1 1 1 1 1 1 0
 0 1 1 1 1 0 0 0 0 0 0 1 1 1 0 0 1 0 1 0 1 1 0 1 1 1 1 0 1 0 0 0 0 1 1 0 0
 0 0 1 1 0 0 1 1 1 1 1 0 0 1 1 0 1 1 1 0 0 1 0 1 1 1 1 0 0 1 1 0 0 0 0 0 1
 1 0 1 1 1 1 1 0 1 0 1 0 0 1 1 1 1 0 1 1 1 0 0 0 1 0 0 1 0 1 1 0 1 0 1 0 0
 0 0 0 1 1 1 0 1 1 0 1 0 1 0 0 1 0 1 0 1 0 0 0 0 1 1 1 0 1 0 1 0 1 1 1 0 1
 0 1 0 1 1 1 1 0 1 1 0 1 1 1 1 1 0 1 1 0 0 1 0 0 0 1 1 0 0 1 0 0 0 1 0 1 1
 0 1 0 1 1 0 0 0 1 0 0 0 1 1 1 0 1 0 1 0 0 1 1 1 0 0 1 1 1 1 1 1 0 0 0 1 1
 0 1 1 0 0 1 0 0 1 1 1 0 1 1 1 1 1 0 0 1 0 1 1 0 1 1 1 0 1 1 0 1 0 0 1 1 1
 0 0 1 1 0 1 0 1 0 0 0 1 1 0 0 0 1 0 0 1 1 1 1 1 1 1 0 1 1 1 0 0 0 1 1 0 1
 1 1 0 1 1 0 1 0 0 0 1 1 1 1 0 0 0 0 1 1 0 0 1 0 1 1 0 

## Step 5:
</h3>Fitting Predictive Model (here I choose 5 classes):</h3>

* Fit the model via .fit() method with attributes X and y.
* And check the accuracy score on whole DataSet.


In [7]:
from sklearn.linear_model import LogisticRegression
log_reg = LogisticRegression()

from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()

from sklearn.svm import SVC
svm = SVC()

from sklearn.naive_bayes import GaussianNB
nb = GaussianNB()

from sklearn.tree import DecisionTreeClassifier
dtf = DecisionTreeClassifier()

log_reg.fit(X,y)
knn.fit(X,y)
svm.fit(X,y)
nb.fit(X,y)
dtf.fit(X,y)

print(log_reg.score(X,y))
print(knn.score(X,y))
print(svm.score(X,y))
print(nb.score(X,y))
print(dtf.score(X,y))

C:\ProgramData\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
C:\ProgramData\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


0.939
0.806
0.955
0.847
0.995


## Step 6 : 
* Splitting into Training and Test set. For this, we need class train_test_split from sklearn.cross_validation. Split can be made 70/30 or 80/20 or 85/15 or 75/25, here I choose 75/25 via “test_size”.
* Fitting a Predictive Model (here I choose 5 classes).
    Fit the model via .fit() method with attributes X_train and y_train.
* And then check the Accuracy score on test set.

In [8]:
from sklearn.model_selection import train_test_split
X_train,X_test , y_train,y_test = train_test_split(X,y,test_size = 0.25)

model1 = log_reg.fit(X_train,y_train)
model2 = knn.fit(X_train,y_train)
model3 = svm.fit(X_train,y_train)
model4 = nb.fit(X_train,y_train)
model5 = dtf.fit(X_train,y_train)

print(log_reg.score(X_test,y_test))
print(knn.score(X_test,y_test))
print(svm.score(X_test,y_test))
print(nb.score(X_test,y_test))
print(dtf.score(X_test,y_test))


0.776
0.672
0.78
0.676
0.728


In [9]:
# Predicting the Test set results 
y_pred1 = model1.predict(X_test) 
y_pred2 = model2.predict(X_test) 
y_pred3 = model3.predict(X_test) 
y_pred4 = model4.predict(X_test) 
y_pred5 = model5.predict(X_test) 
  
print(y_pred1, y_pred2, y_pred3, y_pred4, y_pred5)

[1 0 0 1 0 0 1 1 1 1 0 0 1 1 1 0 0 0 0 1 0 1 0 1 1 0 1 1 1 0 1 0 1 0 1 1 1
 0 0 0 0 0 1 1 1 1 1 1 1 0 0 0 1 0 0 1 0 1 1 1 0 1 1 1 1 0 0 0 1 0 1 0 0 0
 0 1 0 0 0 1 1 1 0 0 1 1 0 1 1 1 0 1 0 1 0 1 0 0 0 1 1 1 0 0 0 0 1 0 0 1 0
 1 1 1 0 1 0 0 1 1 0 0 0 0 1 1 1 1 1 1 0 0 1 1 1 1 0 1 1 1 0 0 1 0 0 1 0 1
 1 1 0 1 1 1 1 0 1 1 0 1 0 0 1 0 1 0 1 1 1 1 1 0 1 0 1 1 0 0 1 1 1 1 1 0 1
 0 0 1 0 0 1 1 1 0 0 0 0 0 1 0 0 1 0 1 0 0 1 1 0 0 0 0 0 1 1 1 0 0 0 1 1 1
 0 0 1 1 0 1 1 1 0 0 0 1 0 1 1 1 0 0 1 1 1 0 1 0 0 0 1 1] [1 0 0 0 0 0 1 1 1 1 1 0 1 0 1 0 0 0 0 0 1 1 1 1 0 0 1 0 1 0 0 0 1 0 1 1 1
 0 0 0 0 0 1 1 1 0 0 1 0 0 0 1 1 0 0 1 0 1 1 0 0 1 1 1 0 0 0 0 1 0 1 0 0 0
 0 1 1 0 1 1 0 1 0 0 1 1 0 1 0 1 0 1 0 0 0 1 0 0 1 1 0 1 1 1 0 0 1 1 0 1 0
 1 1 1 0 0 1 0 1 0 0 0 0 0 1 1 1 1 0 1 0 0 1 0 1 1 0 1 0 0 0 0 1 0 1 0 0 1
 0 1 0 1 0 0 1 0 1 1 0 1 0 1 1 0 0 0 1 1 1 1 0 0 1 0 1 1 0 1 0 1 1 1 0 0 1
 0 1 1 0 0 1 1 1 0 0 0 0 0 1 0 0 0 1 1 0 0 1 0 0 0 0 0 0 0 1 1 1 0 0 1 0 0
 1 0 1 1 0 0 0 1 0 1 0 1 0 0 0 1 0 0 1 1 0

## Step 7: 
To know the accuracy we need confusion matrix


In [11]:
from sklearn.metrics import confusion_matrix 
  
cm1 = confusion_matrix(y_test, y_pred1) 
cm2 = confusion_matrix(y_test, y_pred2) 
cm3 = confusion_matrix(y_test, y_pred3) 
cm4 = confusion_matrix(y_test, y_pred4) 
cm5 = confusion_matrix(y_test, y_pred5) 

print(cm1, cm2, cm3, cm4, cm5)

[[ 91  30]
 [ 26 103]] [[88 33]
 [49 80]] [[103  18]
 [ 37  92]] [[ 61  60]
 [ 21 108]] [[ 79  42]
 [ 26 103]]


## Step 8 :
Precision, Recall, f1 scores on macro:

In [14]:
from sklearn.metrics import precision_score, recall_score, f1_score
p1 = precision_score(y_test, y_pred1,average = 'macro')
r1 = recall_score(y_test, y_pred1,average = 'macro')
f1 = f1_score(y_test, y_pred1,average = 'macro')

p2 = precision_score(y_test, y_pred2,average = 'macro')
r2 = recall_score(y_test, y_pred2,average = 'macro')
f2 = f1_score(y_test, y_pred2,average = 'macro')

p3 = precision_score(y_test, y_pred3,average = 'macro')
r3 = recall_score(y_test, y_pred3,average = 'macro')
f3 = f1_score(y_test, y_pred3,average = 'macro')

p4 = precision_score(y_test, y_pred4,average = 'macro')
r4 = recall_score(y_test, y_pred4,average = 'macro')
f4 = f1_score(y_test, y_pred4,average = 'macro')

p5 = precision_score(y_test, y_pred5,average = 'macro')
r5 = recall_score(y_test, y_pred5,average = 'macro')
f5 = f1_score(y_test, y_pred5,average = 'macro')

print(p1, r1, f1)
print(p2, r2, f2)
print(p3, r3, f3)
print(p4, r4, f4)
print(p5, r5, f5)


0.7761069340016709 0.7752578640527901 0.775482712168837
0.6751501840966345 0.6737138830162086 0.6716637837145236
0.7860389610389611 0.7822089819975655 0.7795732538193945
0.6933797909407666 0.67067076686527 0.664128974473802
0.7313628899835796 0.7256710871932859 0.7254699308830179


## Step 9:
Precision, Recall,f1 scores on micro:

In [15]:
p1 = precision_score(y_test, y_pred1,average = 'micro')
r1 = recall_score(y_test, y_pred1,average = 'micro')
f1 = f1_score(y_test, y_pred1,average = 'micro')

p2 = precision_score(y_test, y_pred2,average = 'micro')
r2 = recall_score(y_test, y_pred2,average = 'micro')
f2 = f1_score(y_test, y_pred2,average = 'micro')

p3 = precision_score(y_test, y_pred3,average = 'micro')
r3 = recall_score(y_test, y_pred3,average = 'micro')
f3 = f1_score(y_test, y_pred3,average = 'micro')

p4 = precision_score(y_test, y_pred4,average = 'micro')
r4 = recall_score(y_test, y_pred4,average = 'micro')
f4 = f1_score(y_test, y_pred4,average = 'micro')

p5 = precision_score(y_test, y_pred5,average = 'micro')
r5 = recall_score(y_test, y_pred5,average = 'micro')
f5 = f1_score(y_test, y_pred5,average = 'micro')

print(p1, r1, f1)
print(p2, r2, f2)
print(p3, r3, f3)
print(p4, r4, f4)
print(p5, r5, f5)


0.776 0.776 0.776
0.672 0.672 0.672
0.78 0.78 0.78
0.676 0.676 0.676
0.728 0.728 0.728
